version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'flights_dev'
    volumes:
      - db-volume:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    ports:
      - '3003:3003'
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules
volumes:
  db-volume:
