version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nextretreat_dev'
    volumes:
      - nextretreat-db-volume:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    ports:
      - '3001:3001'
      - '9229:9229'
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules
volumes:
  nextretreat-db-volume:
