name: Move in progress issues into In progress

on:
  issues:
    types: [labeled]

jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GH_ACCESS_TOKEN }}"
        project-url: "https://github.com/sudolabs-io/next-retreat/projects/1"
        column-name: "In progress"
        label-name: "Status: In Progress"
